#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classroom
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="classroom")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTotal(Elecky.QueryServer.Total instance);
    partial void UpdateTotal(Elecky.QueryServer.Total instance);
    partial void DeleteTotal(Elecky.QueryServer.Total instance);
    partial void InsertTable(Elecky.QueryServer.Table instance);
    partial void UpdateTable(Elecky.QueryServer.Table instance);
    partial void DeleteTable(Elecky.QueryServer.Table instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Elecky.QueryServer.Properties.Settings.Default.classroomConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Elecky.QueryServer.Total> Totals
		{
			get
			{
				return this.GetTable<Elecky.QueryServer.Total>();
			}
		}
		
		public System.Data.Linq.Table<Elecky.QueryServer.Table> Tables
		{
			get
			{
				return this.GetTable<Elecky.QueryServer.Table>();
			}
		}
	}
}
namespace Elecky.QueryServer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Total")]
	public partial class Total : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _classroom;
		
		private int _week_start;
		
		private int _week_end;
		
		private int _weekday;
		
		private int _time;
		
		private System.Nullable<int> _parity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnclassroomChanging(string value);
    partial void OnclassroomChanged();
    partial void Onweek_startChanging(int value);
    partial void Onweek_startChanged();
    partial void Onweek_endChanging(int value);
    partial void Onweek_endChanged();
    partial void OnweekdayChanging(int value);
    partial void OnweekdayChanged();
    partial void OntimeChanging(int value);
    partial void OntimeChanged();
    partial void OnparityChanging(System.Nullable<int> value);
    partial void OnparityChanged();
    #endregion
		
		public Total()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classroom", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string classroom
		{
			get
			{
				return this._classroom;
			}
			set
			{
				if ((this._classroom != value))
				{
					this.OnclassroomChanging(value);
					this.SendPropertyChanging();
					this._classroom = value;
					this.SendPropertyChanged("classroom");
					this.OnclassroomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week_start", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int week_start
		{
			get
			{
				return this._week_start;
			}
			set
			{
				if ((this._week_start != value))
				{
					this.Onweek_startChanging(value);
					this.SendPropertyChanging();
					this._week_start = value;
					this.SendPropertyChanged("week_start");
					this.Onweek_startChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week_end", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int week_end
		{
			get
			{
				return this._week_end;
			}
			set
			{
				if ((this._week_end != value))
				{
					this.Onweek_endChanging(value);
					this.SendPropertyChanging();
					this._week_end = value;
					this.SendPropertyChanged("week_end");
					this.Onweek_endChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weekday", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int weekday
		{
			get
			{
				return this._weekday;
			}
			set
			{
				if ((this._weekday != value))
				{
					this.OnweekdayChanging(value);
					this.SendPropertyChanging();
					this._weekday = value;
					this.SendPropertyChanged("weekday");
					this.OnweekdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parity", DbType="Int")]
		public System.Nullable<int> parity
		{
			get
			{
				return this._parity;
			}
			set
			{
				if ((this._parity != value))
				{
					this.OnparityChanging(value);
					this.SendPropertyChanging();
					this._parity = value;
					this.SendPropertyChanged("parity");
					this.OnparityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Table]")]
	public partial class Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _classroom;
		
		private int _is_free;
		
		private int _now;
		
		private int _max;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private int _state;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnclassroomChanging(string value);
    partial void OnclassroomChanged();
    partial void Onis_freeChanging(int value);
    partial void Onis_freeChanged();
    partial void OnnowChanging(int value);
    partial void OnnowChanged();
    partial void OnmaxChanging(int value);
    partial void OnmaxChanged();
    partial void Onupdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_timeChanged();
    partial void OnstateChanging(int value);
    partial void OnstateChanged();
    #endregion
		
		public Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classroom", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string classroom
		{
			get
			{
				return this._classroom;
			}
			set
			{
				if ((this._classroom != value))
				{
					this.OnclassroomChanging(value);
					this.SendPropertyChanging();
					this._classroom = value;
					this.SendPropertyChanged("classroom");
					this.OnclassroomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_free", DbType="Int NOT NULL")]
		public int is_free
		{
			get
			{
				return this._is_free;
			}
			set
			{
				if ((this._is_free != value))
				{
					this.Onis_freeChanging(value);
					this.SendPropertyChanging();
					this._is_free = value;
					this.SendPropertyChanged("is_free");
					this.Onis_freeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_now", DbType="Int NOT NULL")]
		public int now
		{
			get
			{
				return this._now;
			}
			set
			{
				if ((this._now != value))
				{
					this.OnnowChanging(value);
					this.SendPropertyChanging();
					this._now = value;
					this.SendPropertyChanged("now");
					this.OnnowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max", DbType="Int NOT NULL")]
		public int max
		{
			get
			{
				return this._max;
			}
			set
			{
				if ((this._max != value))
				{
					this.OnmaxChanging(value);
					this.SendPropertyChanging();
					this._max = value;
					this.SendPropertyChanged("max");
					this.OnmaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int NOT NULL")]
		public int state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
